const { wp } = window;
const { unregisterBlockType } = wp.blocks;

wp.domReady( () => {
  unregisterBlockType( 'core-embed/spotify' );
  unregisterBlockType( 'core-embed/animoto' );
  unregisterBlockType( 'core-embed/cloudup' );
  unregisterBlockType( 'core-embed/collegehumor' );
  unregisterBlockType( 'core-embed/dailymotion' );
  unregisterBlockType( 'core-embed/funnyordie' );
  unregisterBlockType( 'core-embed/hulu' );
  unregisterBlockType( 'core-embed/imgur' );
  unregisterBlockType( 'core-embed/issuu' );
  unregisterBlockType( 'core-embed/kickstarter' );
  unregisterBlockType( 'core-embed/meetup-com' );
  unregisterBlockType( 'core-embed/mixcloud' );
  unregisterBlockType( 'core-embed/photobucket' );
  unregisterBlockType( 'core-embed/polldaddy' );
  unregisterBlockType( 'core-embed/reddit' );
  unregisterBlockType( 'core-embed/reverbnation' );
  unregisterBlockType( 'core-embed/screencast' );
  unregisterBlockType( 'core-embed/scribd' );
  unregisterBlockType( 'core-embed/slideshare' );
  unregisterBlockType( 'core-embed/smugmug' );
  unregisterBlockType( 'core-embed/speaker-deck' );
  unregisterBlockType( 'core-embed/ted' );
  unregisterBlockType( 'core-embed/tumblr' );
  unregisterBlockType( 'core-embed/videopress' );
  unregisterBlockType( 'core-embed/wordpress-tv' );
} );
